### ISSUE TITLE
Add freeCodeCamp in technical section

### ISSUE THREAD

**Issue by co16353sidak** [jnv/lists#127]
## freeCodeCamp
Let's add freeCodeCamp in technical section because it has become the goto resource to learn everything web development related.
it is completely open source and completely community sourced, operated and provides 100% free certifications and projects

links :- [Website](https://www.freecodecamp.org), [GitHub](https://github.com/freeCodeCamp/freeCodeCamp)

screenshot :- 
<img width="1254" alt="screenshot 2019-02-02 at 7 44 32 pm" src="https://user-images.githubusercontent.com/35738138/52165154-fa1bad80-2722-11e9-86c2-b1f8400d2fcf.png">

**Comment by jnv** [comment]
Thanks for the suggestion, Sidak. I see that the guide and curriculum are part of the repository, so technically it does conform to the contributing guidelines. Would you like to make a PR for it?

**Comment by co16353sidak** [comment]
Would love to 💯
