### ISSUE TITLE
[joke] Life goal achieved? 

### ISSUE THREAD

**Issue by markogresak** [jnv/lists#45]
[Of course there's an xkcd!](https://xkcd.com/1447/)

**Comment by jirutka** [comment]
+1 :)

**Comment by jnv** [comment]
Heh, there's no 'too meta,' just Stack level too deep. :wink:

Somehow I feel a bit like Forrest Gump. I just felt like doing a list.
![](https://cloud.githubusercontent.com/assets/616767/9294947/76d36f04-445d-11e5-8062-9befaeafe1bd.gif)
