### ISSUE TITLE
Add Illacceptanything

### ISSUE THREAD

**Issue by ProgVal** [jnv/lists#46]
Add https://github.com/illacceptanything/illacceptanything to the list of lists.

I don't know what illacceptanything is a list of, but it's definitely a list.
It also has a list of gifs in its readme.

**Comment by jirutka** [comment]
This isn't a list, but junk...

**Comment by ProgVal** [comment]
list of junk, then?

**Comment by jirutka** [comment]
Well, how is that useful?

**Comment by jnv** [comment]
While I love the illacceptanything project, I would like to keep this list strictly focused on projects which are primarily lists (we are not exactly short on those, as you can see). So I will pass on this one, but thanks for the tip, Valentin!
